# Generated by Django 3.0.6 on 2020-05-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200506_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('fileup', models.FileField(upload_to='new')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
